# fly.toml app configuration file generated for specialist-api on 2025-12-15T17:09:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'specialist-api'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile.prod'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health'
    protocol = 'http'

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health/ready'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
